name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get Package Metadata
        run: |
          echo "PACKAGE_NAME=$(grep -m1 '^name' Cargo.toml | sed -n 's/.*"\([^"]\+\)".*/\1/p')" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$(grep -m1 '^version' Cargo.toml | grep -oP '\d+\.\d+\.\d+')" >> $GITHUB_ENV
      - name: Create Release
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `${process.env.PACKAGE_NAME}-v${process.env.PACKAGE_VERSION}`,
              name: `${process.env.PACKAGE_NAME} v${process.env.PACKAGE_VERSION}`,
              body: 'Please download the appropriate binary for your system and move it somewhere in your path.',
              draft: true,
              prerelease: process.env.PACKAGE_VERSION.split('-').length > 1
            })
            return data.id
  build:
    needs: create-release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: 'ubuntu-20.04'
            target: 'x86_64-unknown-linux-gnu'
          - os: 'ubuntu-20.04'
            target: 'aarch64-unknown-linux-gnu'
          - os: 'macos-latest'
            target: 'x86_64-apple-darwin'
          - os: 'macos-latest'
            target: 'aarch64-apple-darwin'
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Enable ARM64 Architecture (Ubuntu Only)
        if: ${{ matrix.platform.target == 'arch64-unknown-linux-gnu' }}
        run: sudo sudo dpkg --add-architecture arm64 && sudo apt-get update && sudo apt-get install gcc-aarch64-linux-gnu
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}
      - name: Setup Rust Cache
        uses: swatinem/rust-cache@v2
      - name: Compile Binary
        run: cargo build --bins --release --target ${{ matrix.platform.target }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.env.PACKAGE_NAME }}-${{ matrix.platform.target }}
          path: ./target/release/${{ github.env.PACKAGE_NAME }}
